#!/usr/bin/env bash
# This script connects to the server using SSH and a private key

# Set the server IP address
server_ip="8.8.8.8"

# Connect to the server using ssh and private key
ssh -i ~/.ssh/school ubuntu@$server_ip

